version: "3.3"

services:
        django:
                container_name: test_server
                build: .
                command: python manage.py runserver 0.0.0.0:8001
                volumes:
                        - .:/app
                ports:
                        - "8001:8001"
                env_file:
                        - ./.env.dev
