version: "3.3"

services:
        django:
                image: mitchellss/skyprecision:server-vX.X.X 
                container_name: skyprecision_prod_server
                build: 
                        context: .
                        dockerfile: Dockerfile.prod
                command: python manage.py runserver 0.0.0.0:8000
                ports:
                        - "8000:8000"
                env_file:
                        - ./.env.prod
