# Generated by Django 3.1.7 on 2021-03-14 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperature_sensor', '0002_auto_20210310_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temperaturesensor',
            name='temperature',
            field=models.DecimalField(decimal_places=1, default=20, max_digits=6),
        ),
        migrations.AlterField(
            model_name='temperaturesensor',
            name='time',
            field=models.IntegerField(),
        ),
    ]
